CREATE MATERIALIZED VIEW transaction_download_matview_new AS
(
SELECT
    *,
    fy(action_date) AS fiscal_year
FROM
    dblink('broker_server', '(select
            -- unique ids + cols used for unique id
            ''cont_tx_'' || detached_award_proc_unique as generated_unique_transaction_id,
            ''cont_aw_'' ||
              coalesce(agency_id,''-none-'') || ''_'' ||
              coalesce(referenced_idv_agency_iden,''-none-'') || ''_'' ||
              coalesce(piid,''-none-'') || ''_'' ||
              coalesce(parent_award_id,''-none-'') AS generated_unique_award_id,
              action_date,
              a_76_fair_act_action,
              a_76_fair_act_action_desc,
              action_type,
              action_type_description,
              airport_authority,
              alaskan_native_owned_corpo,
              alaskan_native_servicing_i,
              american_indian_owned_busi,
              asian_pacific_american_own,
              awarding_agency_code,
              awarding_agency_name,
              awarding_sub_tier_agency_n,
              black_american_owned_busin,
              c1862_land_grant_college,
              c1890_land_grant_college,
              c1994_land_grant_college,
              c8a_program_participant,
              city_local_government,
              clinger_cohen_act_pla_desc,
              clinger_cohen_act_planning,
              commercial_item_acqui_desc,
              commercial_item_acquisitio,
              commercial_item_test_desc,
              commercial_item_test_progr,
              community_developed_corpor,
              community_development_corp,
              contingency_humanitar_desc,
              contingency_humanitarian_o,
              contract_award_type,
              contract_award_type_desc,
              contract_bundling,
              contract_bundling_descrip,
              contract_financing,
              contract_financing_descrip,
              contracting_officers_desc,
              contracting_officers_deter,
              contracts,
              corporate_entity_not_tax_e,
              corporate_entity_tax_exemp,
              cost_accounting_stand_desc,
              cost_accounting_standards,
              cost_or_pricing_data,
              cost_or_pricing_data_desc,
              council_of_governments,
              country_of_product_or_desc,
              country_of_product_or_serv,
              county_local_government,
              davis_bacon_act,
              davis_bacon_act_descrip,
              dod_claimant_prog_cod_desc,
              dod_claimant_program_code,
              domestic_or_foreign_e_desc,
              domestic_or_foreign_entity,
              domestic_shelter,
              dot_certified_disadvantage,
              economically_disadvantaged,
              educational_institution,
              emerging_small_business,
              epa_designated_produc_desc,
              epa_designated_product,
              evaluated_preference,
              evaluated_preference_desc,
              fair_opportunity_limi_desc,
              fair_opportunity_limited_s,
              fed_biz_opps,
              fed_biz_opps_description,
              federal_action_obligation,
              federal_agency,
              federally_funded_research,
              for_profit_organization,
              foreign_funding,
              foreign_government,
              foreign_owned_and_located,
              foundation,
              funding_agency_code,
              funding_agency_name,
              funding_sub_tier_agency_na,
              government_furnished_desc,
              government_furnished_equip,
              grants,
              hispanic_american_owned_bu,
              hispanic_servicing_institu,
              historically_black_college,
              historically_underutilized,
              hospital_flag,
              housing_authorities_public,
              indian_tribe_federally_rec,
              information_technolog_desc,
              information_technology_com,
              inter_municipal_local_gove,
              interagency_contract_desc,
              interagency_contracting_au,
              international_organization,
              interstate_entity,
              joint_venture_economically,
              joint_venture_women_owned,
              labor_surplus_area_firm,
              legal_entity_zip_last4,
              limited_liability_corporat,
              local_area_set_aside,
              local_area_set_aside_desc,
              local_government_owned,
              major_program,
              manufacturer_of_goods,
              minority_institution,
              minority_owned_business,
              multi_year_contract,
              multi_year_contract_desc,
              multiple_or_single_aw_desc,
              multiple_or_single_award_i,
              municipality_local_governm,
              national_interest_action,
              national_interest_desc,
              native_american_owned_busi,
              native_hawaiian_owned_busi,
              native_hawaiian_servicing,
              nonprofit_organization,
              number_of_actions,
              number_of_offers_received,
              ordering_period_end_date,
              other_minority_owned_busin,
              other_not_for_profit_organ,
              other_statutory_authority,
              other_than_full_and_o_desc,
              other_than_full_and_open_c,
              partnership_or_limited_lia,
              performance_based_se_desc,
              performance_based_service,
              period_of_perf_potential_e,
              period_of_performance_curr,
              period_of_performance_star,
              place_of_manufacture,
              place_of_manufacture_desc,
              place_of_perf_country_desc,
              place_of_perfor_state_desc,
              place_of_performance_locat,
              place_of_performance_zip4a,
              planning_commission,
              port_authority,
              price_evaluation_adjustmen,
              private_university_or_coll,
              program_acronym,
              program_system_or_equ_desc,
              program_system_or_equipmen,
              purchase_card_as_paym_desc,
              purchase_card_as_payment_m,
              receives_contracts_and_gra,
              recovered_materials_s_desc,
              recovered_materials_sustai,
              referenced_idv_agency_desc,
              referenced_idv_modificatio,
              referenced_mult_or_si_desc,
              referenced_mult_or_single,
              research,
              research_description,
              sam_exception,
              sba_certified_8_a_joint_ve,
              school_district_local_gove,
              school_of_forestry,
              sea_transportation,
              sea_transportation_desc,
              self_certified_small_disad,
              service_contract_act,
              service_contract_act_desc,
              service_disabled_veteran_o,
              small_agricultural_coopera,
              small_business_competitive,
              small_disadvantaged_busine,
              sole_proprietorship,
              solicitation_identifier,
              solicitation_procedur_desc,
              solicitation_procedures,
              state_controlled_instituti,
              subchapter_s_corporation,
              subcontinent_asian_asian_i,
              subcontracting_plan,
              subcontracting_plan_desc,
              the_ability_one_program,
              township_local_government,
              transit_authority,
              tribal_college,
              tribally_owned_business,
              type_of_contract_pric_desc,
              type_of_idc,
              type_of_idc_description,
              ultimate_parent_legal_enti,
              ultimate_parent_unique_ide,
              undefinitized_action,
              undefinitized_action_desc,
              us_federal_government,
              us_government_entity,
              us_local_government,
              us_state_government,
              us_tribal_government,
              vendor_doing_as_business_n,
              vendor_fax_number,
              vendor_phone_number,
              veteran_owned_business,
              veterinary_college,
              veterinary_hospital,
              walsh_healey_act,
              walsh_healey_act_descrip,
              woman_owned_business,
              women_owned_small_business
        FROM detached_award_procurement')
        AS transaction
        (
            -- unique ids + cols used for unique id
            generated_unique_transaction_id text,
            generated_unique_award_id text,
            action_date date,
            a_76_fair_act_action text,
            a_76_fair_act_action_desc  text,
            action_type  text,
            action_type_description  text,
            airport_authority  text,
            alaskan_native_owned_corpo  text,
            alaskan_native_servicing_i  text,
            american_indian_owned_busi  text,
            asian_pacific_american_own  text,
            awarding_agency_code  text,
            awarding_agency_name  text,
            awarding_sub_tier_agency_c  text,
            black_american_owned_busin  text,
            c1862_land_grant_college  text,
            c1890_land_grant_college  text,
            c1994_land_grant_college  text,
            c8a_program_participant  text,
            city_local_government  text,
            clinger_cohen_act_pla_desc  text,
            clinger_cohen_act_planning  text,
            commercial_item_acqui_desc  text,
            commercial_item_acquisitio  text,
            commercial_item_test_desc  text,
            commercial_item_test_progr  text,
            community_developed_corpor  text,
            community_development_corp  text,
            contingency_humanitar_desc  text,
            contingency_humanitarian_o  text,
            contract_award_type  text,
            contract_award_type_desc  text,
            contract_bundling  text,
            contract_bundling_descrip  text,
            contract_financing  text,
            contract_financing_descrip  text,
            contracting_officers_desc  text,
            contracting_officers_deter  text,
            contracts  text,
            corporate_entity_not_tax_e  text,
            corporate_entity_tax_exemp  text,
            cost_accounting_stand_desc  text,
            cost_accounting_standards  text,
            cost_or_pricing_data  text,
            cost_or_pricing_data_desc  text,
            council_of_governments  text,
            country_of_product_or_desc  text,
            country_of_product_or_serv  text,
            county_local_government  text,
            davis_bacon_act  text,
            davis_bacon_act_descrip  text,
            dod_claimant_prog_cod_desc  text,
            dod_claimant_program_code  text,
            domestic_or_foreign_e_desc  text,
            domestic_or_foreign_entity  text,
            domestic_shelter  text,
            dot_certified_disadvantage  text,
            economically_disadvantaged  text,
            educational_institution  text,
            emerging_small_business  text,
            epa_designated_produc_desc  text,
            epa_designated_product  text,
            evaluated_preference  text,
            evaluated_preference_desc  text,
            fair_opportunity_limi_desc  text,
            fair_opportunity_limited_s  text,
            fed_biz_opps  text,
            fed_biz_opps_description  text,
            federal_action_obligation numeric ,
            federal_agency  text,
            federally_funded_research  text,
            for_profit_organization  text,
            foreign_funding  text,
            foreign_government  text,
            foreign_owned_and_located  text,
            foundation  text,
            funding_agency_code  text,
            funding_agency_name  text,
            funding_sub_tier_agency_na  text,
            government_furnished_desc  text,
            government_furnished_equip  text,
            grants  text,
            hispanic_american_owned_bu  text,
            hispanic_servicing_institu  text,
            historically_black_college  text,
            historically_underutilized  text,
            hospital_flag  text,
            housing_authorities_public  text,
            indian_tribe_federally_rec  text,
            information_technolog_desc  text,
            information_technology_com  text,
            inter_municipal_local_gove  text,
            interagency_contract_desc  text,
            interagency_contracting_au  text,
            international_organization  text,
            interstate_entity  text,
            joint_venture_economically  text,
            joint_venture_women_owned  text,
            labor_surplus_area_firm  text,
            legal_entity_zip_last4  text,
            limited_liability_corporat  text,
            local_area_set_aside  text,
            local_area_set_aside_desc  text,
            local_government_owned  text,
            major_program  text,
            manufacturer_of_goods  text,
            minority_institution  text,
            minority_owned_business  text,
            multi_year_contract  text,
            multi_year_contract_desc  text,
            multiple_or_single_aw_desc  text,
            multiple_or_single_award_i  text,
            municipality_local_governm  text,
            national_interest_action  text,
            national_interest_desc  text,
            native_american_owned_busi  text,
            native_hawaiian_owned_busi  text,
            native_hawaiian_servicing  text,
            nonprofit_organization  text,
            number_of_actions  text,
            number_of_offers_received  text,
            ordering_period_end_date  text,
            other_minority_owned_busin  text,
            other_not_for_profit_organ  text,
            other_statutory_authority  text,
            other_than_full_and_o_desc  text,
            other_than_full_and_open_c  text,
            partnership_or_limited_lia  text,
            performance_based_se_desc  text,
            performance_based_service  text,
            period_of_perf_potential_e  text,
            period_of_performance_curr  text,
            period_of_performance_star  text,
            place_of_manufacture  text,
            place_of_manufacture_desc  text,
            place_of_perf_country_desc  text,
            place_of_perfor_state_desc  text,
            place_of_performance_locat  text,
            place_of_performance_zip4a  text,
            planning_commission  text,
            port_authority  text,
            price_evaluation_adjustmen  text,
            private_university_or_coll  text,
            program_acronym  text,
            program_system_or_equ_desc  text,
            program_system_or_equipmen  text,
            purchase_card_as_paym_desc  text,
            purchase_card_as_payment_m  text,
            receives_contracts_and_gra  text,
            recovered_materials_s_desc  text,
            recovered_materials_sustai  text,
            referenced_idv_agency_desc  text,
            referenced_idv_modificatio  text,
            referenced_mult_or_si_desc  text,
            referenced_mult_or_single  text,
            research  text,
            research_description  text,
            sam_exception  text,
            sba_certified_8_a_joint_ve  text,
            school_district_local_gove  text,
            school_of_forestry  text,
            sea_transportation  text,
            sea_transportation_desc  text,
            self_certified_small_disad  text,
            service_contract_act  text,
            service_contract_act_desc  text,
            service_disabled_veteran_o  text,
            small_agricultural_coopera  text,
            small_business_competitive  text,
            small_disadvantaged_busine  text,
            sole_proprietorship  text,
            solicitation_identifier  text,
            solicitation_procedur_desc  text,
            solicitation_procedures  text,
            state_controlled_instituti  text,
            subchapter_s_corporation  text,
            subcontinent_asian_asian_i  text,
            subcontracting_plan  text,
            subcontracting_plan_desc  text,
            the_ability_one_program  text,
            township_local_government  text,
            transit_authority  text,
            tribal_college  text,
            tribally_owned_business  text,
            type_of_contract_pric_desc  text,
            type_of_idc  text,
            type_of_idc_description  text,
            ultimate_parent_legal_enti  text,
            ultimate_parent_unique_ide  text,
            undefinitized_action  text,
            undefinitized_action_desc  text,
            us_federal_government  text,
            us_government_entity  text,
            us_local_government  text,
            us_state_government  text,
            us_tribal_government  text,
            vendor_doing_as_business_n  text,
            vendor_fax_number  text,
            vendor_phone_number  text,
            veteran_owned_business  text,
            veterinary_college  text,
            veterinary_hospital  text,
            walsh_healey_act  text,
            walsh_healey_act_descrip  text,
            woman_owned_business  text,
            women_owned_small_business text
        )
);

ALTER MATERIALIZED VIEW IF EXISTS transaction_download_matview RENAME TO transaction_download_matview_old;
ALTER MATERIALIZED VIEW IF EXISTS transaction_download_matview_new RENAME TO transaction_download_matview;
DROP MATERIALIZED VIEW IF EXISTS transaction_download_matview_old;